### ISSUE TITLE
Is it open source?

### ISSUE THREAD

**Issue by ugintl** [healthpotatoes/healthpotatoes#5]
Is it open source?

**Comment by shanesfast** [comment]
Yes :) Feel free to submit some PR's for review. We have just recently started this project and are still working out what features and design choices we want. If you have any questions feel free to ask.

**Comment by shanesfast** [comment]
Also, I am curious as to how you found this project?

**Comment by ugintl** [comment]
On github, I searched "android health" and filtered to recently updated. Sometimes I just search for open source projects.

**Comment by ugintl** [comment]
I like the name

**Comment by shanesfast** [comment]
Thanks :) We like the name too. I will try to work on getting some guidelines for contribution up and a license so it will be officially open source.
